### ISSUE TITLE
search books in subfolders too

### ISSUE THREAD

**Issue by alinelena** [monich/harbour-books#9] opened 2015-08-19 08:51 UTC
At the moment new books are searched and imported only from the root of the search folders (Downloads, Documents/Books, or Books on sdcard)... 
this is somehow related to this https://github.com/monich/harbour-books/issues/3

Alin

**Comment by Mikaela** [comment] 2015-08-19 09:07
I think this is duplicate of #3, not only related to it.

**Comment by alinelena** [comment] 2015-08-19 09:33
My understanding of #3 is that refers to folder organisation within book browsing in interface, rather than searching in subfolders to discover books for import. eg
Downloads/MycoolBook/verycoolbook.epub
this will not be found by check downloads... 
and indeed the issue as you described there comes more when you get to move collections from other readers.

Alin

**Comment by monich** [comment] 2015-08-19 10:08
Are you sure it doesn't find books in subdirectories under Downloads? Search under Downloads is meant to be recursive. Does it find the same book if you move it to Downloads? 

One thing that might confuse you, the app ignores those books in Downloads which are already copied or linked to the library.

**Comment by alinelena** [comment] 2015-08-19 10:34
Ok let me be more detailed... 
I have a device with a sdcard... on sdcard (this is the bit I mistakenly omitted earlier)
Downloads/MycoolBook/verycoolbook.epub
Documents/Books/AnotherBook/anotherverycoolbook.epub
Books/MoreCoolBooks/evercoolerbook.epub
none of these are found.
if I do
Downloads/verycoolbook.epub
Documents/Books/anotherverycoolbook.epub
Books/evercoolerbook.epub
only the one in Books/ is found
Now I realise that it may be that harbour-books does not think of card with such a structure... 

on internal card
Downloads finds them recursively but not in 
Documents/Books/

**Comment by monich** [comment] 2015-08-19 14:44
The "Scan downloads" function was only meant to allow people who don't use command line to import the books they download from the web or receive as email attachments. Browser and mail apps are storing this stuff under ~/Downloads directory in the internal storage. That's where harbour-books app is looking for them when you select "Scan downloads".

Eventually I'm planning to support subdirectories of the ~/Documents/Books and /Books (or whatever, if it's made configurable) on SD card, those will somehow appear as folders/bookshelves in the app. The structure of the books/folders in the UI will reflect the actual directory structure in the internal storage or on the SD card. That's the plan.

**Comment by monich** [comment] 2017-09-07 20:06
Folders are supported since 1.0.10, directory name on the SD-card is configurable since 1.0.16. Marking this one as done.

**Closed by monich** 2017-09-07 20:06 UTC
